name: Update Image on Container Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GB_TK }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/gimbap_backend:latest .
          docker push ghcr.io/${{ github.repository_owner }}/gimbap_backend:latest
